
Lista_credito_brasil = [
    {'Fila':'L','CLiente':'C & M SERVICENTROS SOCIEDAD ANONIMA CERRADA '},
    {'Fila':17,'CLiente':'RED DE COMBUSTIBLES LIQUIDOS SAC REDCOL SAC '},
    {'Fila':18,'CLiente':'SEGURO INTEGRAL DE SALUD'},
    {'Fila':19,'CLiente':'ALMACENERA MERCANTIL SOCIEDAD COMERCIAL DE RESPONSABILIDAD LIMITADA '},
    {'Fila':11,'CLiente':'ALMACENES ASOCIADOS SOCIEDAD ANONIMA CERRADA'}
]

# {'Fila': 16, 'CLiente': 'LUIS RODRIGUEZ'},
