config_celdas_grifos = {
    'BRASIL': [
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '32. BRASIL',  'Dato': 'Hoja_registro_ventas'},
        {'ReadNum': 12,     'ReadLetra': 'P'  ,'Write': 'C',  'Dato': 'Total_venta_acumulada'},
        {'ReadNum': 8,      'ReadLetra': 'P'  ,'Write': 'D',  'Dato': 'Venta_GPL'},
        {'ReadNum': 9,      'ReadLetra': 'P'  ,'Write': 'E',  'Dato': 'Venta_GNV'},
        {'ReadNum': 28,     'ReadLetra': 'P'  ,'Write': 'F',  'Dato': 'Recaudo_Cofide_GNV'},
        {'ReadNum': 17,     'ReadLetra': 'P'  ,'Write': 'AO', 'Dato': 'Total_Tarjeta_de_Credito_Liquidos'},
        {'ReadNum': 18,     'ReadLetra': 'P'  ,'Write': 'AP', 'Dato': 'Total_Tarjeta_de_Credito_GLP'},
        {'ReadNum': 19,     'ReadLetra': 'P'  ,'Write': 'AQ', 'Dato': 'Total_Tarjeta_de_Credito_GNV'},
        {'ReadNum': 29,     'ReadLetra': 'P'  ,'Write': 'BY', 'Dato': 'Gastos'},
        {'ReadNum': 31,     'ReadLetra': 'P'  ,'Write': 'AY', 'Dato': 'Ventas_con_transferencia'},
        {'ReadNum': '',     'ReadLetra': 'Q'  ,'Write': '',   'Dato': 'Tipo_Hermes'},
        {'ReadNum': '',     'ReadLetra': 'O'  ,'Write': '',   'Dato': 'Importe_Hermes'},
        {'ReadNum': 'AUTO', 'ReadLetra': 'O'  ,'Write': 'AX', 'Dato': 'Hermes_monto_liquido'},
        {'ReadNum': 'AUTO', 'ReadLetra': 'O'   ,'Write': 'BD', 'Dato': 'Hermes_monto_GLP'},
        {'ReadNum': 'AUTO', 'ReadLetra': 'O'  ,'Write': 'BE', 'Dato': 'Hermes_monto_GNV1'},
        {'ReadNum': 'AUTO', 'ReadLetra': 'O'  ,'Write': 'BF', 'Dato': 'Hermes_monto_GNV2'},
        {'ReadNum': '',     'ReadLetra': 'Q'   ,'Write': '',   'Dato': 'TipoDescuento'},
        {'ReadNum': '',     'ReadLetra': 'S'   ,'Write': 'AO',   'Dato': 'DescuentoLiquidos'},
        {'ReadNum': '',     'ReadLetra': 'S'   ,'Write': 'AP',   'Dato': 'DescuentoGLP'},
        {'ReadNum': 26,     'ReadLetra': 'P'   ,'Write': 'AR',   'Dato': 'ErrorMaquina'}
    ],
    'PUENTE PIEDRA': [
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '01. PUENTE P.',  'Dato': 'Hoja_registro_ventas'},
        {'ReadNum': 11,     'ReadLetra': 'P'  ,'Write': 'C',  'Dato': 'Total_venta_acumulada'},
        {'ReadNum': 8,      'ReadLetra': 'P'  ,'Write': 'D',  'Dato': 'Venta_GPL'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Venta_GNV'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Recaudo_Cofide_GNV'},
        {'ReadNum': 16,     'ReadLetra': 'P'  ,'Write': 'AK', 'Dato': 'Total_Tarjeta_de_Credito_Liquidos'},
        {'ReadNum': 17,     'ReadLetra': 'P'  ,'Write': 'AL', 'Dato': 'Total_Tarjeta_de_Credito_GLP'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Total_Tarjeta_de_Credito_GNV'},
        {'ReadNum': 28,     'ReadLetra': 'P'  ,'Write': 'BN', 'Dato': 'Gastos'},
        {'ReadNum': 30,     'ReadLetra': 'P'  ,'Write': 'AP', 'Dato': 'Ventas_con_transferencia'},
        {'ReadNum': '',     'ReadLetra': 'Q'  ,'Write': '',   'Dato': 'Tipo_Hermes'},
        {'ReadNum': '',     'ReadLetra': 'O'  ,'Write': '',   'Dato': 'Importe_Hermes'},
        {'ReadNum': 'AUTO', 'ReadLetra': 'O'  ,'Write': 'AT', 'Dato': 'Hermes_monto_liquido'},
        {'ReadNum': 'AUTO', 'ReadLetra': 'O'  ,'Write': 'BA', 'Dato': 'Hermes_monto_GLP'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Hermes_monto_GNV1'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Hermes_monto_GNV2'},
        {'ReadNum': 'AUTO',     'ReadLetra': 'Q'   ,'Write': '',   'Dato': 'TipoDescuento'},
        {'ReadNum': 'AUTO',     'ReadLetra': 'S'   ,'Write': 'AO',   'Dato': 'DescuentoLiquidos'},
        {'ReadNum': 'AUTO',     'ReadLetra': 'S'   ,'Write': 'AP',   'Dato': 'DescuentoGLP'},
        {'ReadNum': 26,     'ReadLetra': 'P'   ,'Write': 'AR',   'Dato': 'ErrorMaquina'}
    ],
    'CHILCA': [
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '04. CHILCA',  'Dato': 'Hoja_registro_ventas'},
        {'ReadNum': 11,     'ReadLetra': 'P'  ,'Write': 'C',  'Dato': 'Total_venta_acumulada'},
        {'ReadNum': 8,      'ReadLetra': 'P'  ,'Write': 'D',  'Dato': 'Venta_GPL'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Venta_GNV'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Recaudo_Cofide_GNV'},
        {'ReadNum': 16,     'ReadLetra': 'P'  ,'Write': 'AQ', 'Dato': 'Total_Tarjeta_de_Credito_Liquidos'},
        {'ReadNum': 17,     'ReadLetra': 'P'  ,'Write': 'AR', 'Dato': 'Total_Tarjeta_de_Credito_GLP'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': 'AS', 'Dato': 'Total_Tarjeta_de_Credito_GNV'},
        {'ReadNum': 'AUTO',     'ReadLetra': 'Q'   ,'Write': '',   'Dato': 'TipoDescuento'},
        {'ReadNum': 'AUTO',     'ReadLetra': 'S'   ,'Write': 'AU',   'Dato': 'DescuentoLiquidos'},
        {'ReadNum': 'AUTO',     'ReadLetra': 'S'   ,'Write': 'AV',   'Dato': 'DescuentoGLP'},
        {'ReadNum': 26,     'ReadLetra': 'P'   ,'Write': 'AY',   'Dato': 'ErrorMaquina'},
        {'ReadNum': 'AUTO', 'ReadLetra': 'O'  ,'Write': 'BA', 'Dato': 'Hermes_monto_liquido'},
        {'ReadNum': 30,     'ReadLetra': 'P'  ,'Write': 'BB', 'Dato': 'Ventas_con_transferencia'},
        {'ReadNum': 'AUTO', 'ReadLetra': 'O'  ,'Write': 'BF', 'Dato': 'Hermes_monto_GLP'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Hermes_monto_GNV1'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Hermes_monto_GNV2'},
        {'ReadNum': 28,     'ReadLetra': 'P'  ,'Write': 'BZ', 'Dato': 'Gastos'},
        {'ReadNum': '',     'ReadLetra': 'Q'  ,'Write': '',   'Dato': 'Tipo_Hermes'},
        {'ReadNum': '',     'ReadLetra': 'O'  ,'Write': '',   'Dato': 'Importe_Hermes'}
    ],
    'VIRU': [
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '14.VIRU',  'Dato': 'Hoja_registro_ventas'},
        {'ReadNum': 11,     'ReadLetra': 'P'  ,'Write': 'C',  'Dato': 'Total_venta_acumulada'},
        {'ReadNum': 8,      'ReadLetra': 'P'  ,'Write': 'D',  'Dato': 'Venta_GPL'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Venta_GNV'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Recaudo_Cofide_GNV'},
        {'ReadNum': 16,     'ReadLetra': 'P'  ,'Write': 'AJ', 'Dato': 'Total_Tarjeta_de_Credito_Liquidos'},
        {'ReadNum': 17,     'ReadLetra': 'P'  ,'Write': 'AK', 'Dato': 'Total_Tarjeta_de_Credito_GLP'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '', 'Dato': 'Total_Tarjeta_de_Credito_GNV'},
        {'ReadNum': 'AUTO',     'ReadLetra': 'Q'   ,'Write': '',   'Dato': 'TipoDescuento'},
        {'ReadNum': 'AUTO',     'ReadLetra': 'S'   ,'Write': 'AN',   'Dato': 'DescuentoLiquidos'},
        {'ReadNum': 'AUTO',     'ReadLetra': 'S'   ,'Write': 'AO',   'Dato': 'DescuentoGLP'},
        {'ReadNum': 26,     'ReadLetra': 'P'   ,'Write': 'AQ',   'Dato': 'ErrorMaquina'},
        {'ReadNum': 'AUTO', 'ReadLetra': 'O'  ,'Write': 'AS', 'Dato': 'Hermes_monto_liquido'},
        {'ReadNum': 30,     'ReadLetra': 'P'  ,'Write': 'AT', 'Dato': 'Ventas_con_transferencia'},
        {'ReadNum': 'AUTO', 'ReadLetra': 'O'  ,'Write': 'AY', 'Dato': 'Hermes_monto_GLP'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Hermes_monto_GNV1'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Hermes_monto_GNV2'},
        {'ReadNum': 28,     'ReadLetra': 'P'  ,'Write': 'BS', 'Dato': 'Gastos'},
        {'ReadNum': '',     'ReadLetra': 'Q'  ,'Write': '',   'Dato': 'Tipo_Hermes'},
        {'ReadNum': '',     'ReadLetra': 'O'  ,'Write': '',   'Dato': 'Importe_Hermes'}
    ],
    'MAKITA': [
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '43. MAKITA',  'Dato': 'Hoja_registro_ventas'},
        {'ReadNum': 12,     'ReadLetra': 'P'  ,'Write': 'C',  'Dato': 'Total_venta_acumulada'},
        {'ReadNum': 8,      'ReadLetra': 'P'  ,'Write': 'D',  'Dato': 'Venta_GPL'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Venta_GNV'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Recaudo_Cofide_GNV'},
        {'ReadNum': 17,     'ReadLetra': 'P'  ,'Write': 'AI', 'Dato': 'Total_Tarjeta_de_Credito_Liquidos'},
        {'ReadNum': 18,     'ReadLetra': 'P'  ,'Write': 'AJ', 'Dato': 'Total_Tarjeta_de_Credito_GLP'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '', 'Dato': 'Total_Tarjeta_de_Credito_GNV'},
        {'ReadNum': 'AUTO',     'ReadLetra': 'Q'   ,'Write': '',   'Dato': 'TipoDescuento'},
        {'ReadNum': 'AUTO',     'ReadLetra': 'S'   ,'Write': 'AM',   'Dato': 'DescuentoLiquidos'},
        {'ReadNum': 'AUTO',     'ReadLetra': 'S'   ,'Write': 'AN',   'Dato': 'DescuentoGLP'},
        {'ReadNum': 26,     'ReadLetra': 'P'   ,'Write': 'AQ',   'Dato': 'ErrorMaquina'},
        {'ReadNum': 'AUTO', 'ReadLetra': 'O'  ,'Write': 'AS', 'Dato': 'Hermes_monto_liquido'},
        {'ReadNum': 30,     'ReadLetra': 'P'  ,'Write': 'AT', 'Dato': 'Ventas_con_transferencia'},
        {'ReadNum': 'AUTO', 'ReadLetra': 'O'  ,'Write': 'AX', 'Dato': 'Hermes_monto_GLP'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Hermes_monto_GNV1'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Hermes_monto_GNV2'},
        {'ReadNum': 28,     'ReadLetra': 'P'  ,'Write': 'BR', 'Dato': 'Gastos'},
        {'ReadNum': '',     'ReadLetra': 'Q'  ,'Write': '',   'Dato': 'Tipo_Hermes'},
        {'ReadNum': '',     'ReadLetra': 'O'  ,'Write': '',   'Dato': 'Importe_Hermes'}
    ],
    'SAN PABLO': [
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '44.SAN PABLO',  'Dato': 'Hoja_registro_ventas'},
        {'ReadNum': 12,     'ReadLetra': 'P'  ,'Write': 'C',  'Dato': 'Total_venta_acumulada'},
        {'ReadNum': 8,      'ReadLetra': 'P'  ,'Write': 'D',  'Dato': 'Venta_GPL'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Venta_GNV'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Recaudo_Cofide_GNV'},
        {'ReadNum': 17,     'ReadLetra': 'P'  ,'Write': 'AH', 'Dato': 'Total_Tarjeta_de_Credito_Liquidos'},
        {'ReadNum': 18,     'ReadLetra': 'P'  ,'Write': 'AI', 'Dato': 'Total_Tarjeta_de_Credito_GLP'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '', 'Dato': 'Total_Tarjeta_de_Credito_GNV'},
        {'ReadNum': 'AUTO',     'ReadLetra': 'Q'   ,'Write': '',   'Dato': 'TipoDescuento'},
        {'ReadNum': 'AUTO',     'ReadLetra': 'S'   ,'Write': 'AL',   'Dato': 'DescuentoLiquidos'},
        {'ReadNum': 'AUTO',     'ReadLetra': 'S'   ,'Write': 'AM',   'Dato': 'DescuentoGLP'},
        {'ReadNum': 26,     'ReadLetra': 'P'   ,'Write': 'AP',   'Dato': 'ErrorMaquina'},
        {'ReadNum': 'AUTO', 'ReadLetra': 'O'  ,'Write': 'AR', 'Dato': 'Hermes_monto_liquido'},
        {'ReadNum': 31,     'ReadLetra': 'P'  ,'Write': 'AS', 'Dato': 'Ventas_con_transferencia'},
        {'ReadNum': 'AUTO', 'ReadLetra': 'O'  ,'Write': 'AU', 'Dato': 'Hermes_monto_GLP'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Hermes_monto_GNV1'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Hermes_monto_GNV2'},
        {'ReadNum': 29,     'ReadLetra': 'P'  ,'Write': 'BO', 'Dato': 'Gastos'},
        {'ReadNum': '',     'ReadLetra': 'Q'  ,'Write': '',   'Dato': 'Tipo_Hermes'},
        {'ReadNum': '',     'ReadLetra': 'O'  ,'Write': '',   'Dato': 'Importe_Hermes'}
    ],
    'HUANCHACO': [
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '54. HUANCHACO',  'Dato': 'Hoja_registro_ventas'},
        {'ReadNum': 12,     'ReadLetra': 'P'  ,'Write': 'C',  'Dato': 'Total_venta_acumulada'},
        {'ReadNum': 8,      'ReadLetra': 'P'  ,'Write': 'D',  'Dato': 'Venta_GPL'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Venta_GNV'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Recaudo_Cofide_GNV'},
        {'ReadNum': 17,     'ReadLetra': 'P'  ,'Write': 'AK', 'Dato': 'Total_Tarjeta_de_Credito_Liquidos'},
        {'ReadNum': 18,     'ReadLetra': 'P'  ,'Write': 'AL', 'Dato': 'Total_Tarjeta_de_Credito_GLP'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '', 'Dato': 'Total_Tarjeta_de_Credito_GNV'},
        {'ReadNum': 'AUTO',     'ReadLetra': 'Q'   ,'Write': '',   'Dato': 'TipoDescuento'},
        {'ReadNum': 'AUTO',     'ReadLetra': 'S'   ,'Write': 'AO',   'Dato': 'DescuentoLiquidos'},
        {'ReadNum': 'AUTO',     'ReadLetra': 'S'   ,'Write': 'AP',   'Dato': 'DescuentoGLP'},
        {'ReadNum': 26,     'ReadLetra': 'P'   ,'Write': 'AR',   'Dato': 'ErrorMaquina'},
        {'ReadNum': 'AUTO', 'ReadLetra': 'O'  ,'Write': 'AT', 'Dato': 'Hermes_monto_liquido'},
        {'ReadNum': 31,     'ReadLetra': 'P'  ,'Write': 'AU', 'Dato': 'Ventas_con_transferencia'},
        {'ReadNum': 'AUTO', 'ReadLetra': 'O'  ,'Write': 'AY', 'Dato': 'Hermes_monto_GLP'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Hermes_monto_GNV1'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Hermes_monto_GNV2'},
        {'ReadNum': 29,     'ReadLetra': 'P'  ,'Write': 'BS', 'Dato': 'Gastos'},
        {'ReadNum': '',     'ReadLetra': 'Q'  ,'Write': '',   'Dato': 'Tipo_Hermes'},
        {'ReadNum': '',     'ReadLetra': 'O'  ,'Write': '',   'Dato': 'Importe_Hermes'}
    ],
    'ENACE': [
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '55.ENACE',  'Dato': 'Hoja_registro_ventas'},
        {'ReadNum': 11,     'ReadLetra': 'P'  ,'Write': 'C',  'Dato': 'Total_venta_acumulada'},
        {'ReadNum': 8,      'ReadLetra': 'P'  ,'Write': 'D',  'Dato': 'Venta_GPL'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Venta_GNV'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Recaudo_Cofide_GNV'},
        {'ReadNum': 16,     'ReadLetra': 'P'  ,'Write': 'AK', 'Dato': 'Total_Tarjeta_de_Credito_Liquidos'},
        {'ReadNum': 17,     'ReadLetra': 'P'  ,'Write': 'AL', 'Dato': 'Total_Tarjeta_de_Credito_GLP'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '', 'Dato': 'Total_Tarjeta_de_Credito_GNV'},
        {'ReadNum': 'AUTO',     'ReadLetra': 'Q'   ,'Write': '',   'Dato': 'TipoDescuento'},
        {'ReadNum': 'AUTO',     'ReadLetra': 'S'   ,'Write': 'AO',   'Dato': 'DescuentoLiquidos'},
        {'ReadNum': 'AUTO',     'ReadLetra': 'S'   ,'Write': 'AP',   'Dato': 'DescuentoGLP'},
        {'ReadNum': 26,     'ReadLetra': 'P'   ,'Write': 'AS',   'Dato': 'ErrorMaquina'},
        {'ReadNum': 'AUTO', 'ReadLetra': 'O'  ,'Write': 'AU', 'Dato': 'Hermes_monto_liquido'},
        {'ReadNum': 30,     'ReadLetra': 'P'  ,'Write': 'AV', 'Dato': 'Ventas_con_transferencia'},
        {'ReadNum': 'AUTO', 'ReadLetra': 'O'  ,'Write': 'BA', 'Dato': 'Hermes_monto_GLP'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Hermes_monto_GNV1'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Hermes_monto_GNV2'},
        {'ReadNum': 28,     'ReadLetra': 'P'  ,'Write': 'BU', 'Dato': 'Gastos'},
        {'ReadNum': '',     'ReadLetra': 'Q'  ,'Write': '',   'Dato': 'Tipo_Hermes'},
        {'ReadNum': '',     'ReadLetra': 'O'  ,'Write': '',   'Dato': 'Importe_Hermes'}
    ],
    'ACAPULCO': [
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '56. ACAPULCO',  'Dato': 'Hoja_registro_ventas'},
        {'ReadNum': 11,     'ReadLetra': 'P'  ,'Write': 'C',  'Dato': 'Total_venta_acumulada'},
        {'ReadNum': 8,      'ReadLetra': 'P'  ,'Write': 'D',  'Dato': 'Venta_GPL'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Venta_GNV'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Recaudo_Cofide_GNV'},
        {'ReadNum': 16,     'ReadLetra': 'P'  ,'Write': 'AJ', 'Dato': 'Total_Tarjeta_de_Credito_Liquidos'},
        {'ReadNum': 17,     'ReadLetra': 'P'  ,'Write': 'AK', 'Dato': 'Total_Tarjeta_de_Credito_GLP'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '', 'Dato': 'Total_Tarjeta_de_Credito_GNV'},
        {'ReadNum': 'AUTO',     'ReadLetra': 'Q'   ,'Write': '',   'Dato': 'TipoDescuento'},
        {'ReadNum': 'AUTO',     'ReadLetra': 'S'   ,'Write': 'AN',   'Dato': 'DescuentoLiquidos'},
        {'ReadNum': 'AUTO',     'ReadLetra': 'S'   ,'Write': 'AO',   'Dato': 'DescuentoGLP'},
        {'ReadNum': 26,     'ReadLetra': 'P'   ,'Write': 'AR',   'Dato': 'ErrorMaquina'},
        {'ReadNum': 'AUTO', 'ReadLetra': 'O'  ,'Write': 'AT', 'Dato': 'Hermes_monto_liquido'},
        {'ReadNum': 30,     'ReadLetra': 'P'  ,'Write': 'AU', 'Dato': 'Ventas_con_transferencia'},
        {'ReadNum': 'AUTO', 'ReadLetra': 'O'  ,'Write': 'AZ', 'Dato': 'Hermes_monto_GLP'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Hermes_monto_GNV1'},
        {'ReadNum': '',     'ReadLetra': ''   ,'Write': '',   'Dato': 'Hermes_monto_GNV2'},
        {'ReadNum': 28,     'ReadLetra': 'P'  ,'Write': 'BT', 'Dato': 'Gastos'},
        {'ReadNum': '',     'ReadLetra': 'Q'  ,'Write': '',   'Dato': 'Tipo_Hermes'},
        {'ReadNum': '',     'ReadLetra': 'O'  ,'Write': '',   'Dato': 'Importe_Hermes'}
    ]
}

# REVISAR POSISION
 #{'ReadNum': 30,     'ReadLetra': 'P'  ,'Write': 'AP', 'Dato': 'Ventas_con_transferencia'},


# config_celdas_grifos = {
#     'BRASIL': [
#         {'Fila': '32. BRASIL',  'Dato': 'Hoja_registro_ventas'},
#         {'Fila': 'C',  'Dato': 'Total_venta_acumulada'},
#         {'Fila': 'D',  'Dato': 'Venta_GPL'},
#         {'Fila': 'E',  'Dato': 'Venta_GNV'},
#         {'Fila': 'F',  'Dato': 'Recaudo_Cofide_GNV'},
#         {'Fila': 'AO', 'Dato': 'Total_Tarjeta_de_Credito_Liquidos'},
#         {'Fila': 'AP', 'Dato': 'Total_Tarjeta_de_Credito_GLP'},
#         {'Fila': 'AQ', 'Dato': 'Total_Tarjeta_de_Credito_GNV'},
#         {'Fila': 'BY', 'Dato': 'Gastos'},
#         {'Fila': 'AY', 'Dato': 'Ventas_con_transferencia'},
#         {'Fila': 'AX', 'Dato': 'Hermes_monto_liquido'},
#         {'Fila': 'BD', 'Dato': 'Hermes_monto_GLP'},
#         {'Fila': 'BE', 'Dato': 'Hermes_monto_GNV1'},
#         {'Fila': 'BF', 'Dato': 'Hermes_monto_GNV2'}
#     ],
#     'PUENTE PIEDRA': [
#         {'Fila': '01. PUENTE P.',  'Dato': 'Hoja_registro_ventas'},
#         {'Fila': 'C',  'Dato': 'Total_venta_acumulada'},
#         {'Fila': 'D',  'Dato': 'Venta_GPL'},
#         {'Fila': '',  'Dato': 'Venta_GNV'},
#         {'Fila': '',  'Dato': 'Recaudo_Cofide_GNV'},
#         {'Fila': 'AK', 'Dato': 'Total_Tarjeta_de_Credito_Liquidos'},
#         {'Fila': 'AL', 'Dato': 'Total_Tarjeta_de_Credito_GLP'},
#         {'Fila': '', 'Dato': 'Total_Tarjeta_de_Credito_GNV'},
#         {'Fila': 'BN', 'Dato': 'Gastos'},
#         {'Fila': 'AV', 'Dato': 'Ventas_con_transferencia'},
#         {'Fila': 'AT', 'Dato': 'Hermes_monto_liquido'},
#         {'Fila': 'BA', 'Dato': 'Hermes_monto_GLP'},
#         {'Fila': '', 'Dato': 'Hermes_monto_GNV1'},
#         {'Fila': '', 'Dato': 'Hermes_monto_GNV2'}
#     ]
    
# }
