
Lista_credito_brasil = [
   {'Fila':'H','CLiente':'COMMUNICATIONS AND SYSTEMS DEVELOPMENT SOCIEDAD ANONIMA CERRADA'},
   {'Fila':'I','CLiente':'FUERO MILITAR POLICIAL'},
   {'Fila':'J','CLiente':'ALMACENES ASOCIADOS SOCIEDAD ANONIMA CERRADA'},
   {'Fila':'L','CLiente':'C & M SERVICENTROS SOCIEDAD ANONIMA CERRADA'},
   {'Fila':'N','CLiente':'FONDO NACIONAL DE DESARROLLO PESQUERO'},
   {'Fila':'T','CLiente':'RED DE COMBUSTIBLES LIQUIDOS SAC REDCOL SAC'},
   {'Fila':'U','CLiente':'UNIDAD EJECUTORA 004 - FONDO DE COOPERACION PARA EL DESARROLLO SOCIAL'},
   {'Fila':'V','CLiente':'MUNICIPALIDAD DE JESUS MARIA'},
   {'Fila':'Y','CLiente':'SEGURO INTEGRAL DE SALUD'},
   {'Fila':'AC','CLiente':'INSTITUTO NACIONAL DE SALUD DEL NIñO'},
   {'Fila':'AL','CLiente':'ALMACENERA MERCANTIL SOCIEDAD COMERCIAL DE RESPONSABILIDAD LIMITADA'}
]
