config_columna_creditos= {
   'BRASIL': [
      {'Columna':'H','CLiente':'COMMUNICATIONS AND SYSTEMS DEVELOPMENT SOCIEDAD ANONIMA CERRADA'},
      {'Columna':'I','CLiente':'FUERO MILITAR POLICIAL'},
      {'Columna':'J','CLiente':'ALMACENES ASOCIADOS SOCIEDAD ANONIMA CERRADA'},
      {'Columna':'L','CLiente':'C & M SERVICENTROS SOCIEDAD ANONIMA CERRADA'},
      {'Columna':'M','CLiente':'IMPORTACIONES HUARMEY S.A.C.-IHUASAC'},
      {'Columna':'N','CLiente':'FONDO NACIONAL DE DESARROLLO PESQUERO'},
      {'Columna':'O','CLiente':'PROGRAMA DE EMPLEO TEMPORAL \\LLAMKASUN PERÚ\\'},
      {'Columna':'T','CLiente':'RED DE COMBUSTIBLES LIQUIDOS SAC REDCOL SAC'},
      {'Columna':'U','CLiente':'UNIDAD EJECUTORA 004 - FONDO DE COOPERACION PARA EL DESARROLLO SOCIAL'},
      {'Columna':'V','CLiente':'MUNICIPALIDAD DE JESUS MARIA'},
      {'Columna':'Y','CLiente':'SEGURO INTEGRAL DE SALUD'},
      {'Columna':'AC','CLiente':'INSTITUTO NACIONAL DE SALUD DEL NIñO'},
      {'Columna':'AL','CLiente':'ALMACENERA MERCANTIL SOCIEDAD COMERCIAL DE RESPONSABILIDAD LIMITADA'}
   ],
   'PUENTE PIEDRA': [
      {'Columna':'K','CLiente':'PUNTO GAS SOCIEDAD ANONIMA CERRADA - PUNTO GAS S.A.C.'},
      {'Columna':'R','CLiente':'RED DE COMBUSTIBLES LIQUIDOS SAC REDCOL SAC'},
      {'Columna':'M','CLiente':'C & M SERVICENTROS SOCIEDAD ANONIMA CERRADA'},
      {'Columna':'N','CLiente':'PETRO WORLD TRANSPORTES DEL PERU SOCIEDAD ANONIMA CERRADA'},
      {'Columna':'H','CLiente':'PETROTHOR SOCIEDAD ANONIMA CERRADA'}
   ],
   'CHILCA': [
      {'Columna':'K','CLiente':'PUNTO GAS SOCIEDAD ANONIMA CERRADA - PUNTO GAS S.A.C.'},
      {'Columna':'R','CLiente':'RED DE COMBUSTIBLES LIQUIDOS SAC REDCOL SAC'},
      {'Columna':'M','CLiente':'C & M SERVICENTROS SOCIEDAD ANONIMA CERRADA'},
      {'Columna':'N','CLiente':'PETRO WORLD TRANSPORTES DEL PERU SOCIEDAD ANONIMA CERRADA'},
      {'Columna':'H','CLiente':'PETROTHOR SOCIEDAD ANONIMA CERRADA'}
   ]
}